#pragma config(Sensor, in1,    pot,            sensorPotentiometer)
#pragma config(Sensor, dgtl8,  touchl,         sensorTouch)
#pragma config(Sensor, dgtl9,  Bump,           sensorTouch)
#pragma config(Sensor, dgtl10, pneuLock,       sensorDigitalOut)
#pragma config(Sensor, dgtl11, pneuLiftL,      sensorDigitalOut)
#pragma config(Sensor, dgtl12, pneuLiftR,      sensorDigitalOut)
#pragma config(Sensor, I2C_1,  nCoderleft,     sensorNone)
#pragma config(Sensor, I2C_2,  nCoderRight,    sensorNone)
#pragma config(Motor,  port2,           driveL1,       tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port3,           driveL2,       tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port4,           liftL1,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           liftL2,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           liftR1,        tmotorVex393, openLoop)
#pragma config(Motor,  port7,           liftR2,        tmotorVex393, openLoop)
#pragma config(Motor,  port8,           driveR1,       tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port9,           collector,     tmotorVex393, openLoop)
#pragma config(Motor,  port10,          driveR2,       tmotorVex393HighSpeed, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"
#include "Variables.c"
#include "Functions.c"
//#include "LCD_pre_auton.c"

void pre_auton()	{
	SensorValue[pneuLock] = 0;
	SensorValue[pneuLiftL] = SensorValue[pneuLiftR] = 1;
  //StartTask(autonChooser);
  #include "LCD_pre_auton.c"
	}

task autonomous()	{
//#include "blue-mid-1.c"
//#include "red-mid-1.c"
#include "auton.c"
}

task usercontrol()	{

	while (true)	{

#include "teleop.c"
	}
}
