#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    pot,            sensorPotentiometer)
#pragma config(Sensor, dgtl8,  touchl,         sensorTouch)
#pragma config(Sensor, dgtl9,  Bump,           sensorTouch)
#pragma config(Sensor, dgtl10, pneuLock,       sensorDigitalOut)
#pragma config(Sensor, dgtl11, pneuLiftL,      sensorDigitalOut)
#pragma config(Sensor, dgtl12, pneuLiftR,      sensorDigitalOut)
#pragma config(Sensor, I2C_1,  nCoderleft,     sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  nCoderRight,    sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           driveL1,       tmotorVex393HighSpeed, PIDControl, reversed, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port3,           driveL2,       tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port4,           liftL1,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           liftL2,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           liftR1,        tmotorVex393, openLoop)
#pragma config(Motor,  port7,           liftR2,        tmotorVex393, openLoop)
#pragma config(Motor,  port8,           driveR1,       tmotorVex393HighSpeed, PIDControl, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port9,           collector,     tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port10,          driveR2,       tmotorVex393HighSpeed, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"
#include "Variables.c"
#include "Functions.c"


void pre_auton()	{
	SensorValue[pneuLock] = 0;
	SensorValue[pneuLiftL] = SensorValue[pneuLiftR] = 1;
#include"LCD_pre_auton.c"
}

task autonomous()	{
#include"auton.c"
}

task usercontrol()	{
	while (true)	{
#include"teleop.c"
	}
}
