#pragma config(Sensor, in1,    					pot,           sensorPotentiometer)
#pragma config(Sensor, dgtl7,  					solenoid,      sensorDigitalOut)
#pragma config(Motor,  port1,           hdrive,        tmotorVex393, openLoop)
#pragma config(Motor,  port2,           driveR1,       tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           driveL1,       tmotorVex393, openLoop)
#pragma config(Motor,  port4,           LiftL2,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           LiftL1,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           LiftR1,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           LiftR2,        tmotorVex393, openLoop)
#pragma config(Motor,  port8,           driveR2,       tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           driveL2,       tmotorVex393, openLoop)
#pragma config(Motor,  port10,          belt,          tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//																																																									 //
//																																																									 //
//			This is the RobotC code for 2587K - DiscoBots Kappa written by Abhishek Prajapati	for 2014-15                //
//			                                 VRC Game - VEX Skyrise																											 //
//																																																									 //
//																	© Copyright 2014-15 DiscoBots.org																				         //
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"

void liftSet(int speed)
{
	motor[LiftL1] = motor[LiftL2] = motor[LiftR1] = motor[LiftR2] = speed;
}

void moveLift(int height,float time)
{ClearTimer(T1);
	while(time1[T1]< time*1000){

  SensorValue[pot] = height;
}
liftSet(0);
}


void pre_auton()
{

}
task autonomous()
{
	///////////////////////////////Blue//////////////////////////////
	motor[driveR1] = 127;
	motor[driveR2] = 127;
	motor[driveL1] = 127;
	motor[driveL2] = 127;
	wait1Msec(575);

	motor[driveR1] = 0;
	motor[driveR2] = 0;
	motor[driveL1] = 0;
	motor[driveL2] = 0;

	motor[belt]= 127;
	wait1Msec(1600);
	motor[belt]=0;

	motor[driveR1] = 127;
	motor[driveR2] = 127;
	motor[driveL1] = 127;
	motor[driveL2] = 127;
	wait1Msec(1000);

	motor[driveR1] = 0;
	motor[driveR2] = 0;
	motor[driveL1] = 0;
	motor[driveL2] = 0;

	motor[driveR1] = 127;
	motor[driveR2] = 127;
	motor[driveL1] = -127;
	motor[driveL2] = -127;
	wait1Msec(650);

	motor[driveR1] = 0;
	motor[driveR2] = 0;
	motor[driveL1] = 0;
	motor[driveL2] = 0;

  motor[driveR1] = -127;
	motor[driveR2] = -127;
	motor[driveL1] = -127;
	motor[driveL2] = -127;
	wait1Msec(100);

	motor[driveR1] = 0;
	motor[driveR2] = 0;
	motor[driveL1] = 0;
	motor[driveL2] = 0;

	while(SensorValue[pot] < 1800) {
		motor(LiftL1) = motor(LiftR1) = 127;
		motor(LiftL2)= motor(LiftR2)= -127;
	}

	motor(LiftL1) = motor(LiftR1) = 20;
	motor(LiftL2)= motor(LiftR2)= -20;


	motor[driveR1] = 0;
	motor[driveR2] = 0;


	motor[belt]= -127;
	wait1Msec(2000);
	motor[belt]=0;

	motor[driveR1] = -127;
	motor[driveR2] = -127;
	motor[driveL1] = -127;
	motor[driveL2] = -127;
	wait1Msec(200);

	motor[driveR1] = 0;
	motor[driveR2] = 0;
	motor[driveL1] = 0;
	motor[driveL2] = 0;

///////////////////////////////Red//////////////////////////////
	motor[driveR1] = 127;
	motor[driveR2] = 127;
	motor[driveL1] = 127;
	motor[driveL2] = 127;
	wait1Msec(575);

	motor[driveR1] = 0;
	motor[driveR2] = 0;
	motor[driveL1] = 0;
	motor[driveL2] = 0;

	motor[belt]= 127;
	wait1Msec(1600);
	motor[belt]=0;

	motor[driveR1] = 127;
	motor[driveR2] = 127;
	motor[driveL1] = 127;
	motor[driveL2] = 127;
	wait1Msec(1000);

	motor[driveR1] = 0;
	motor[driveR2] = 0;
	motor[driveL1] = 0;
	motor[driveL2] = 0;

	motor[driveR1] = -127;
	motor[driveR2] = -127;
	motor[driveL1] = 127;
	motor[driveL2] = 127;
	wait1Msec(650);

	motor[driveR1] = 0;
	motor[driveR2] = 0;
	motor[driveL1] = 0;
	motor[driveL2] = 0;

  motor[driveR1] = -127;
	motor[driveR2] = -127;
	motor[driveL1] = -127;
	motor[driveL2] = -127;
	wait1Msec(100);

	motor[driveR1] = 0;
	motor[driveR2] = 0;
	motor[driveL1] = 0;
	motor[driveL2] = 0;

	while(SensorValue[pot] < 1800) {
		motor(LiftL1) = motor(LiftR1) = 127;
		motor(LiftL2)= motor(LiftR2)= -127;
	}

	motor(LiftL1) = motor(LiftR1) = 20;
	motor(LiftL2)= motor(LiftR2)= -20;


	motor[driveR1] = 0;
	motor[driveR2] = 0;


	motor[belt]= -127;
	wait1Msec(2000);
	motor[belt]=0;

	motor[driveR1] = -127;
	motor[driveR2] = -127;
	motor[driveL1] = -127;
	motor[driveL2] = -127;
	wait1Msec(200);

	motor[driveR1] = 0;
	motor[driveR2] = 0;
	motor[driveL1] = 0;
	motor[driveL2] = 0;
}
task usercontrol()
{
	////////////////////////////////////////////*Drivetrain*//////////////////////////////////////////////////////
	while(1 == 1)
  {
  	int rightStick = vexRT[Ch2];
  	int leftStick = vexRT[Ch3];

  	if(rightStick > 10 || rightStick < -10)
  	{
    	motor[driveR1] = rightStick;
   		motor[driveR2] = rightStick;
  	}
  	else
  	{
  		motor[driveR1] = 0;
  		motor[driveR2] = 0;
  	}

  	if(leftStick > 10 || leftStick < -10){
    	motor[driveL1] = leftStick;
   		motor[driveL2] = leftStick;
  	}
  	else
  	{
  		motor[driveL1] = 0;
   		motor[driveL2] = 0;
  	}
	////////////////////////////////////////////*Lift*//////////////////////////////////////////////////////

  	if(vexRT[Btn5U] == 1) {
	  motor(LiftL1) = motor(LiftR1) = 127;
	  motor(LiftL2)= motor(LiftR2)= -127;
		}
		else if(vexRT[Btn5D] == 1) {
		motor(LiftL1) = motor(LiftR1) = -127;
		motor(LiftL2) = motor(LiftR2) = 127;
		}
				else {
		motor(LiftL1) = motor(LiftR1) = 20;
		motor(LiftL2) = motor(LiftR2) = 20;
		}
 ////////////////////////////////////////////*Collector*//////////////////////////////////////////////////////
		if(vexRT[Btn6U] == 1) {
	  motor(belt) = 127;

		}
		else if(vexRT[Btn6D] == 1) {
		motor(belt) = -127;
		}
		else {
		motor(belt)= 20;

		}
///////////////////////////////////////////*hdrive*//////////////////////////////////////////////////////
		if(vexRT[Btn8L] == 1) {
	  motor(hdrive) = 127;

		}
		else if(vexRT[Btn8R] == 1) {
		motor(hdrive) = -127;
		}
		else {
		motor(hdrive)= 0;
		}

		////////////////////////////////////////////*Pneumatics*//////////////////////////////////////////////////////


		if(vexRT[Btn7U] == 1)	{           // If button 8U is pressed:
		SensorValue[solenoid] = 1;  			//...activates the solenoid.
		}
		else if (vexRT[Btn7D] ==1) {			// If button 8D is  pressed:
		SensorValue[solenoid] = 0;  			//...deactivates the solenoid.
		}

	/////////////////////////////////Turn 45 for Skyrise/////////////////////////////////////////////////////////

		if(vexRT[Btn7L] == 1) {
	 	motor[driveR1] = -127;
		motor[driveR2] = -127;
		motor[driveL1] = 127;
		motor[driveL2] = 127;
		wait1Msec(500);

		motor[hdrive] = 127;
		wait1Msec(60);
		}
		else if(vexRT[Btn7R] == 1) {

		motor[driveR1] = 127;
		motor[driveR2] = 127;
		motor[driveL1] = -127;
		motor[driveL2] = -127;
		wait1Msec(500);
		motor[hdrive] = -127;
		wait1Msec(60);
		}
}




