#pragma config(Sensor, in7,    aPot,           sensorPotentiometer)
#pragma config(Sensor, in8,    pot,            sensorPotentiometer)
#pragma config(Sensor, dgtl6,  touch3,         sensorTouch)
#pragma config(Sensor, dgtl7,  touchL,         sensorTouch)
#pragma config(Sensor, dgtl9,  touchR,         sensorTouch)
#pragma config(Sensor, dgtl10, pLock,          sensorDigitalOut)
#pragma config(Sensor, dgtl11, wing,           sensorDigitalOut)
#pragma config(Sensor, dgtl12, Catapult,       sensorDigitalOut)
#pragma config(Motor,  port1,           collectorL,    tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port2,           driveL2,       tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port3,           driveL1,       tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port4,           liftL2,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           liftL1,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           liftR1,        tmotorVex393, openLoop)
#pragma config(Motor,  port7,           liftR2,        tmotorVex393, openLoop)
#pragma config(Motor,  port8,           driveR1,       tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port9,           driveR2,       tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port10,          collectorR,    tmotorVex393HighSpeed, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)


#include "Vex_Competition_Includes.c"
#include "Z-Vars.c"
#include "Z-Functions.c"


void pre_auton()	{

	SensorValue[wing] = 0;
	SensorValue[Catapult] = 0;
	SensorValue[pLock] = 0;

}

task autonomous()	{
	//#include "blue-mid-2ZK"
	//#include "red-mid-1Z.c"
	//#include "red-hang-1Z.c"
	//#include "red-mid-2Z.c"
	//#include "red-hang-2Z.c"

	#include "blue-mid-1Z.c"
	//#include "blue-hang-1Z.c"
	//#include "blue-mid-2Z.c"
	//#include "blue-hang-2Z.c"

	//#include "programSelectZ.c"
}

task usercontrol()	{
	ClearTimer(T4);
	while (true)	{
#include "Z-teleop.c"
	}
}
