#pragma config(Sensor, in1,    pot,            sensorPotentiometer)
#pragma config(Sensor, dgtl1,  touchL,         sensorTouch)
#pragma config(Motor,  port1,           collectorL,    tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port2,           driveL2,       tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port3,           driveL1,       tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port4,           liftL2,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           liftL1,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           liftR1,        tmotorVex393, openLoop)
#pragma config(Motor,  port7,           liftR2,        tmotorVex393, openLoop)
#pragma config(Motor,  port8,           driveR1,       tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port9,           driveR2,       tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port10,          collectorR,    tmotorVex393HighSpeed, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c";
#include "varZ.c";
#include "funcLibZ.c";

void pre_auton() {} // end pre-auton

task autonomous()	{
#include "autonZ.c";
} // end auton

task usercontrol()	{
	while (true)	{
		#include "userControlZ.c";
	} // end while
} // end userControl
